language: python

python:
  - "2.7"
  - "3.5"

install:
  - pip install git+https://github.com/Princeton-CDH/piffle.git@feature/python3-compatibility#egg=piffle
  - pip install -e .
  - pip install -e '.[test]'
  - pip install codecov
  - cp ci/testsettings.py testsettings.py
  - python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> testsettings.py

script:
  - py.test --cov=djiffy

after_success:
  - codecov
