language: python

python:
  - "3.5"
  - "3.6"

env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
  - pip install -q Django==$DJANGO
  - pip install -e .
  - pip install -e '.[test]'
  - pip install codecov
  - cp ci/testsettings.py testsettings.py
  - python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> testsettings.py

script:
  - py.test --cov=djiffy

after_success:
  - codecov
