# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IfBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('short_id', models.CharField(max_length=255)),
                ('uri', models.URLField()),
                ('created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IIIF Book',
            },
        ),
        migrations.CreateModel(
            name='IfPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('short_id', models.CharField(max_length=255)),
                ('uri', models.URLField()),
                ('iiif_image_id', models.URLField()),
                ('thumbnail', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='djiffy.IfBook')),
            ],
            options={
                'verbose_name': 'IIIF Page',
                'ordering': ['book', 'order'],
            },
        ),
    ]
