# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 13:32
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djiffy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='extra_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
