# Generated by Django 3.2.25 on 2025-03-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djiffy', '0003_extra_data_revisions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='extra_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='extra_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
